CREATE TABLE ANIMAL(
	ANIMAL_ID VARCHAR2(20) NOT NULL,
	ANIMAL_NAME VARCHAR2(20) NOT NULL,
	NICKNAME VARCHAR2(20),
	AGE NUMBER(3,0),
	GENDER VARCHAR2(20) NOT NULL,
	CURRENT_CONDITION VARCHAR2(40),
	CATEGORY VARCHAR2(20),
    ARRIVAL_PLACE VARCHAR2(20),
	ARRIVAL_DATE DATE,
	BREEDING_STATUS VARCHAR2(30),
	ENDANGERED_STATUS VARCHAR2(20) NOT NULL,
	ENVIRONMENT VARCHAR2(40),
	PREVIOUS_AFFECTED_DISEASES VARCHAR2(60),
	PRICE NUMBER (20,0),
	LIFESPAN VARCHAR2(20) NOT NULL,
	SPECIAL_DIMENSION VARCHAR2(30),
	a_HEIGHT NUMBER(3,0),
	a_weight NUMBER(20,0),
	DEATH VARCHAR2(20),
	CAUSE VARCHAR2(20),
	CAGE_NO VARCHAR2(40) ,
	SPECIES VARCHAR2(20),
	CONSTRAINT ANIMAL_ANIMAL_ID_PK PRIMARY KEY(ANIMAL_ID),
	CONSTRAINT ANIMAL_CAGE_NO_FK FOREIGN KEY(CAGE_NO) REFERENCES CAGE(CAGE_NO) ON DELETE CASCADE,
	CONSTRAINT ANIMAL_SPECIES_FK FOREIGN KEY(SPECIES) REFERENCES TAXONOMY(SPECIES) ON DELETE CASCADE
);
INSERT INTO ANIMAL (ANIMAL_ID, ANIMAL_NAME , NICKNAME,AGE,GENDER,CURRENT_CONDITION,CATEGORY,ARRIVAL_PLACE,ARRIVAL_DATE,BREEDING_STATUS,ENDANGERED_STATUS,ENVIRONMENT,PREVIOUS_AFFECTED_DISEASES ,PRICE,LIFESPAN ,SPECIAL_DIMENSION,a_HEIGHT,a_weight,DEATH,CAUSE,CAGE_NO,SPECIES) 
VALUES ('G_01','Girafes', 'no',10,'male','good','mammal','Australia',to_date('15-JUN-2019','DD-MM-YYYY'),' May and August ','not endangered','grass field','cold',1000000,'25','5.80m (neck)',100,1100,'no','no','7','camelopardalis');
INSERT INTO ANIMAL (ANIMAL_ID, ANIMAL_NAME , NICKNAME,AGE,GENDER,CURRENT_CONDITION,CATEGORY,ARRIVAL_PLACE,ARRIVAL_DATE,BREEDING_STATUS,ENDANGERED_STATUS,ENVIRONMENT,PREVIOUS_AFFECTED_DISEASES ,PRICE,LIFESPAN ,SPECIAL_DIMENSION,a_HEIGHT,a_weight,DEATH,CAUSE,CAGE_NO,SPECIES) 
VALUES ('T_01','Tiger', 'no',10,'male','good','mammal','Bangladesh',to_date('15-JUN-2019','DD-MM-YYYY'),' May and August ','endangered','grass field','cold',1000000,'25','5.80m (neck)',100,1100,'no','no','5','tigris');

CREATE TABLE CAGE(
	CAGE_NO VARCHAR2(40) NOT NULL ,
	CAGE_LOCATION VARCHAR2(20) NOT NULL,
	MAX_CAPACITY NUMBER(4,0),
	CLEANING_INTERVAL VARCHAR2(40)NOT NULL,
  	CAGE_HEIGHT NUMBER(5,0), 
  	CAGE_WEIGHT NUMBER(5,0), 
  	CAGE_LENGTH NUMBER(5,0),
  	CLEAN_STATUS VARCHAR2(10), 
  	LAST_CLEANING_DATE VARCHAR2(40), 
	CONSTRAINT CAGE_CAGE_NO_PK PRIMARY KEY(CAGE_NO)
);
INSERT INTO CAGE (CAGE_NO,CAGE_LOCATION,MAX_CAPACITY,CLEANING_INTERVAL,CAGE_HEIGHT,CAGE_WEIGHT,CAGE_LENGTH,CLEAN_STATUS,LAST_CLEANING_DATE) 
VALUES (07,'EAST-1',8,6,50,30,40,'clean','16-JUN-2022');
 
 CREATE table TAXONOMY (
    GENUS      VARCHAR2(20) NOT NULL,
    SPECIES    VARCHAR2(20) NOT NULL,
    "KINGDOM"    VARCHAR2(20),
    "PHYLUM"     VARCHAR2(20),
    "T_CLASS"    VARCHAR2(20),
    "FAMILY"     VARCHAR2(20),
    "T_ORDER"    VARCHAR2(20)
);
 


INSERT INTO TAXONOMY (GENUS,SPECIES,KINGDOM,PHYLUM,T_CLASS,FAMILY,T_ORDER) 
VALUES ('Giraffa' ,'camelopardalis' ,'Animalia' , '	Chordata','Mammalia' ,'Giraffidae' , 'Artiodactyla');

