DROP TABLE ANIMAL
DROP TABLE CAGE
DROP TABLE MUSEUM
DROP TABLE LOOK_AFTER
DROP TABLE TAKE_CARE
DROP TABLE ANIMAL_DIET
DROP TABLE EMPLOYEE ;
DROP TABLE INCOME ;
DROP TABLE TAXONOMY ;
Drop TABLE Visitor_Info;
Drop TABLE VisitorInfo_PhoneNo;
Drop TABLE Visitor_visitingDates;
Drop TABLE Complaints;
Drop TABLE Visitor_Complaints;
Drop TABLE Ticket_info;
Drop TABLE Employee_Complaints;
Drop TABLE ComplaintsAboutCage;
DROP TABLE FOOD;
DROP TABLE PROVIDES;
DROP TABLE SUPPLIER_FOOD;
DROP TABLE FOOD_SUPPLIER_PHONE_NUMBER;
DROP TABLE FOOD_SUPPLIER;
DROP TABLE FOOD_COST;
DROP TABLE RESEARCH_WORK;
DROP TABLE RESEARCH_ON_ANIMAL;
DROP TABLE RESEARCH_ON_MUSEUM;
DROP TABLE ZOO_INFO;
DROP TABLE VACCINE;
DROP TABLE EXPENDITURE ;