CREATE TABLE  "EMPLOYEE" 
   (	"EMPLOYEE_ID" VARCHAR2(100) NOT NULL ENABLE, 
	"EMPLOYEE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(10), 
	"JOB_TYPE" VARCHAR2(50), 
	"DESIGNATION" VARCHAR2(100), 
	"SALARY" NUMBER(20,5), 
	"JOINING_DATE" VARCHAR2(100), 
	"DOB" VARCHAR2(100), 
	 CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID") ENABLE
   ) ;