CREATE TABLE  "LOOK_AFTER" 
   (	"CAGE_NO" VARCHAR2(20) NOT NULL ENABLE, 
	"EMPLOYEE_ID" VARCHAR2(20)
   ) ;ALTER TABLE  "LOOK_AFTER" ADD CONSTRAINT "LOOK_AFTER_CAGE_NO_FK" FOREIGN KEY ("CAGE_NO")
	  REFERENCES  "CAGE" ("CAGE_NO") ON DELETE CASCADE ENABLE;ALTER TABLE  "LOOK_AFTER" ADD CONSTRAINT "LOOK_AFTER_EMPLOYEE_ID_FK" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES  "EMPLOYEE" ("EMPLOYEE_ID") ON DELETE CASCADE ENABLE;