CREATE TABLE VACCINE (
    VACCINE_ID VARCHAR2(20),
    VACCINE_NAME VARCHAR2(20),
    ARRIVAL_DATE DATE,
    VACCINE_TYPE VARCHAR2(20),
    ENVIRONMENT_TYPE VARCHAR2(20),
    CURE_DISEASES VARCHAR2(20),
    EXPIARY_DATE DATE,
    PRODUCTION_DATE DATE,
    CONSTRAINT VACCINE_ID_PK PRIMARY KEY(VACCINE_ID)
);